# Generated by Django 4.2.7 on 2023-12-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_rename_berted_by_leaverequest_verted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ISD', 'ISD'), ('S&L', 'S&L'), ('RM&E', 'RM&E'), ('Administration', 'Administration'), ('Account', 'Account')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
