# Generated by Django 4.2.7 on 2023-12-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('holiday', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ISD', 'ISD'), ('S&L', 'S&L'), ('RM&E', 'RM&E'), ('Administration', 'Administration'), ('Account', 'Account'), ('HR', 'HR')], max_length=255, null=True),
        ),
    ]
