# Generated by Django 4.2.7 on 2023-12-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_holidays_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reasons for leave'),
        ),
    ]
