# Generated by Django 4.2.7 on 2023-12-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_leaverequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
